# Create
# <r-lst.RData> containing
# 	r_lst    : each list element contains the changed files name
# 	r_lstdate: each element represents date
# <flfreq.txt> containing
# 	flfreq   : each row contains file name
#       	   the column contains frequency

# r_lst <- list(); r_lstdate <- NULL
HOME <- Sys.getenv("HOME")
DirCode <- "github"

load(file.path(HOME, DirCode, "r_lst.RData"))
x  <- scan("/tmp/tmp.txt", "") # generated by r-source.sh
r_lst <- c(r_lst, list(f=x))
r_lstdate <- c(r_lstdate, as.character(Sys.Date()))
save(r_lst, r_lstdate, file = file.path(HOME, DirCode, "r_lst.RData"))

flfreq <- table(unlist(r_lst))
file.copy(file.path(HOME, DirCode, "flfreq.txt"), file.path(HOME, DirCode, "flfreq_old.txt"))
write.table(flfreq, file =file.path(HOME, DirCode, "flfreq.txt"), 
            row.names=F, col.names=F, quote=F)

